spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      mvc:
        routes:
          - id: lms
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/lms/**
          - id: cms
            uri: http://localhost:8092
            predicates:
              - Path=/api/vi/cms/**
server:
  port: 8222

eureka:
  client:
    register-with-eureka: false
