server:
  port: 8090

spring:
  application:
    name: lms-service

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    username: root
    password: Chaocaunhe1@
    url: jdbc:mysql://localhost:3306/lms
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



