server:
  port: ${PORT:8000}

spring:
  application:
    name: lms-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    username: udfx8gd2r28omxh0
    password: cac3FVA7OEoWRsQdkULi
    url: jdbc:mysql://b2rdypb6kbojeaqiz6ab-mysql.services.clever-cloud.com:3306/b2rdypb6kbojeaqiz6ab
    driver-class-name: com.mysql.cj.jdbc.Driver
