server:
  port: 8000

spring:
  application:
    name: lms-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    username: root
    password: FUPisHYNaaskpTHxPkKTBRYlCPOjPqjs
    url: jdbc:mysql://tramway.proxy.rlwy.net:49555/lms
    driver-class-name: com.mysql.cj.jdbc.Driver
cloudinary:
  cloud-name: demxhfvfs
  api-key: 482747477385664
  api-secret: iaiotSS140T9Rhg_2tG8zRFDA1g
