server:
  port: 8090

spring:
  application:
    name: lms-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    username: root
    password: Chaocaunhe1@
    url: jdbc:mysql://localhost:3306/lms
    database-platform: org.hibernate.dialect.MySQLDialect
